// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate, studio, etc.) needs a *direct* (non-pooled)
    // connection — Supabase's transaction pooler doesn't support the prepared
    // statements migrations rely on. The app itself connects with the pooled
    // DATABASE_URL instead, in src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
